openapi: 3.0.3
info:
  title: jmoney
  description: "a funny application that implements the jar system"
  termsOfService: todo
  contact:
    email: todo@todo.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1-SNAPSHOT
externalDocs:
  description: todo
  url: https://docs.jmoney.jzeratul.tech
servers:
  - url: https://jmoney.jzeratul.tech
tags:
  - name: jar
    description: Operations about the user's jars
  - name: payment
    description: Operations about the user's payments
paths:
  /jmoney/jars:
    get:
      tags:
        - jar
      summary: Get all user's jars
      description: Get all user's jars
      operationId: getJars
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WebJar'
      x-codegen-request-body-name: body
    post:
      tags:
        - jar
      summary: Each submitted object has a 'status' that specifies if the jar should be created or deleted
      description: A user can have one or more jars. With this endpoint we create new jars and we return all the jars the user has, after the update
      operationId: updateJars
      requestBody:
        description: update the user's jars
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/WebJar'
        required: true
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WebJar'
      x-codegen-request-body-name: body

  /jmoney/jars/{encodedJarId}/payments:
    get:
      tags:
        - payment
      summary: Get payments for jar
      operationId: getPayments
      parameters:
        - name: encodedJarId
          in: path
          description: 'The Id for the jar, encoded. '
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WebJarPayment'
    post:
      tags:
        - payment
      summary: Each submitted object has a 'status' that specifies if the payment should be created or deleted
      description: A jar may have any number of payments. With this method we create payments. The request supports any number of payments.
      operationId: updatePayments
      parameters:
        - name: encodedJarId
          in: path
          description: 'The Id for the jar, encoded. '
          required: true
          schema:
            type: string
      requestBody:
        description: Create payments for the jar
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/WebJarPayment'
        required: true
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WebJarPayment'
      x-codegen-request-body-name: body

components:
  schemas:

    Status:
      type: string
      enum:
        - existing
        - new
        - deleted
        - updated

    WebJar:
      type: object
      properties:
        id:
          type: number
          format: int32
        name:
          type: string
        percent:
          type: number
        variant:
          type: string
        createdAt:
          type: string
          format: date-time
        status:
          $ref: '#/components/schemas/Status'

    WebJarPayment:
      type: object
      properties:
        id:
          type: number
          format: int32
        reason:
          type: string
        amount:
          type: number
        createdAt:
          type: string
          format: date-time
        paymentDate:
          type: string
          format: date-time
        status:
          $ref: '#/components/schemas/Status'
