openapi: 3.0.3
info:
  title: jmoney
  description: "a funny application that implements the jar system"
  termsOfService: todo
  contact:
    email: todo@todo.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1-SNAPSHOT
externalDocs:
  description: todo
  url: https://docs.jmoney.jzeratul.tech
servers:
  - url: https://jmoney.jzeratul.tech
tags:
  - name: jar
    description: Operations about the user's jars
  - name: payment
    description: Operations about the user's payments
  - name: income
    description: Operations about the user's incomes
  - name: user
    description: Operations related to users
  - name: testdata
    description: This api is used to generate test data on demand, I do not want to write an INIT SQL

paths:

  /jmoney/jars:
    get:
      tags:
        - jar
      summary: Get all user's jars
      description: Get all user's jars
      operationId: getJars
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WebJar'
      x-codegen-request-body-name: body
    post:
      tags:
        - jar
      summary: Each submitted object has a 'status' that specifies if the jar should be created or deleted
      description: Each submitted object has a 'status' that specifies if the jar should be created or deleted
      operationId: updateJars
      requestBody:
        description: update the user's jars
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/WebJar'
        required: true
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WebJar'
      x-codegen-request-body-name: body

  /jmoney/income:
    get:
      tags:
        - income
      summary: Get all user's incomes
      description: Get all user's incomes
      operationId: getIncomes
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WebIncome'
      x-codegen-request-body-name: body
    post:
      tags:
        - income
      summary: Each submitted object has a 'status' that specifies if the income should be created or deleted
      description: Each submitted object has a 'status' that specifies if the income should be created or deleted
      operationId: updateIncomes
      requestBody:
        description: update the user's jars
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/WebIncome'
        required: true
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WebIncome'
      x-codegen-request-body-name: body

  /jmoney/jars/payments:
    get:
      tags:
        - payment
      summary: Get payments for jar
      description: Get payments for jar
      operationId: getPayments
      parameters:
        - name: encodedJarId
          in: header
          description: 'The Id for the jar, encoded. '
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WebJarPayment'
    post:
      tags:
        - payment
      summary: Each submitted object has a 'status' that specifies if the payment should be created or deleted
      description: Each submitted object has a 'status' that specifies if the payment should be created or deleted
      operationId: updatePayments
      parameters:
        - name: encodedJarId
          in: header
          description: 'The Id for the jar, encoded. '
          required: true
          schema:
            type: string
      requestBody:
        description: Create payments for the jar
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/WebJarPayment'
        required: true
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WebJarPayment'
      x-codegen-request-body-name: body

  /signup:
    post:
      tags:
        - user
      summary: Use it to signup a user
      description: Use it to signup a user
      operationId: signup
      requestBody:
        description: Create payments for the jar
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebUser'
        required: true
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebUser'
      x-codegen-request-body-name: body

  /login:
    post:
      tags:
        - user
      summary: Use it to signup a user
      description: Use it to signup a user
      operationId: login
      requestBody:
        description: Create payments for the jar
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebUser'
        required: true
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebUser'
      x-codegen-request-body-name: body

  /jmoney/random-data-generator:
    post:
      tags:
        - testdata
      summary: Generate random test data
      description: Generate random test data
      operationId: generateTestdata
      responses:
        default:
          description: successful operation
      x-codegen-request-body-name: body

components:
  schemas:

    Status:
      type: string
      enum:
        - new
        - deleted
        - updated

    WebJar:
      type: object
      required:
        - name
        - percent
        - variant
      properties:
        id:
          type: string
        name:
          type: string
          minLength: 3
          maxLength: 100
        percent:
          type: number
          minimum: 0
        variant:
          type: string
        createdAt:
          type: string
          format: date-time
        status:
          $ref: '#/components/schemas/Status'

    WebJarPayment:
      type: object
      required:
        - jarid
        - reason
        - amount
      properties:
        id:
          type: string
        jarid:
          type: string
        reason:
          type: string
          minLength: 3
          maxLength: 100
        amount:
          type: number
          minimum: 0
        createdAt:
          type: string
          format: date-time
        paymentDate:
          type: string
          format: date-time
        status:
          $ref: '#/components/schemas/Status'

    WebIncome:
      type: object
      required:
        - source
        - amount
      properties:
        id:
          type: string
        source:
          type: string
          minLength: 3
          maxLength: 100
        amount:
          type: number
          minimum: 0
        createdAt:
          type: string
          format: date-time
        incomeDate:
          type: string
          format: date-time
        status:
          $ref: '#/components/schemas/Status'

    WebUser:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          minLength: 4
          maxLength: 30
        password:
          type: string
          minLength: 4
          maxLength: 100