
spring:
  application:
    name: jmoney-service
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    generate-ddl: false
    database: mysql
  flyway:
    enabled: true
    baseline-on-migrate: false

  datasource:
    url: jdbc:mysql://localhost:3306/jmoneydb?serverTimezone=UTC
    username: root
    password: ENC(M439ts/xMmOVTxBY/g0jilF1its32GiiYt2j5Rpftj2AV5RuqLTh8EkyXHWGIwie)
    hikari:
      maximum-pool-size: 3

logging:
  level:
    root: info

springdoc:
  api-docs:
    path: /jmoney-api-docs

#openapi:
#  jmoney:
#    base-path: the-test