CREATE TABLE juser (
      USERID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT
    , USERNAME VARCHAR (60) NOT NULL
    , PASSWORD VARCHAR (100) NOT NULL
    , CREATED_AT DATETIME NOT NULL
    , UNIQUE KEY(USERNAME)
    , INDEX (CREATED_AT)
) ENGINE=MyISAM DEFAULT CHARSET=UTF8MB4;

CREATE TABLE jar (
      JARID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT
    , USERID BIGINT NOT NULL
    , NAME VARCHAR (60) NOT NULL
    , PERCENT DECIMAL(2, 2) NOT NULL
    , VARIANT VARCHAR (60) NOT NULL
    , CREATED_AT DATETIME NOT NULL
    , UNIQUE KEY(USERID, NAME)
    , INDEX (CREATED_AT)
    , CONSTRAINT JAR_JUSER_FK FOREIGN KEY (USERID) REFERENCES juser(USERID)
) ENGINE=MyISAM DEFAULT CHARSET=UTF8MB4;

CREATE TABLE payment (
      PAYMENTID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT
    , JARID BIGINT NOT NULL
    , REASON VARCHAR (50) NOT NULL
    , AMOUNT DECIMAL(10, 2) NOT NULL
    , PAYMENT_DATE DATETIME NOT NULL
    , CREATED_AT DATETIME NOT NULL
    , INDEX (CREATED_AT)
    , INDEX (PAYMENT_DATE)
    , CONSTRAINT PAYMENT_JAR_FK FOREIGN KEY (JARID) REFERENCES jar(JARID)
) ENGINE=MyISAM DEFAULT CHARSET=UTF8MB4;

CREATE TABLE income (
      INCOMEID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT
    , USERID BIGINT NOT NULL
    , SOURCE VARCHAR (200) NOT NULL
    , AMOUNT DECIMAL(10, 2) NOT NULL
    , INCOME_DATE DATETIME NOT NULL
    , CREATED_AT DATETIME NOT NULL
    , INDEX (CREATED_AT)
    , CONSTRAINT INCOME_JUSER_FK FOREIGN KEY (USERID) REFERENCES juser(USERID)
) ENGINE=MyISAM DEFAULT CHARSET=UTF8MB4;