version: '3.8'

# Define services
services:

  mysqldatabase:
    image: mysql/mysql-server:latest
    container_name: mysqldb-tests
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: jmoneydb
      MYSQL_USER: root
      MYSQL_PASSWORD: jmoney
      MYSQL_ROOT_PASSWORD: jmoney
    networks:
      - database

  jmoney-service:
    image: jmoney-server:1.0
    depends_on:
      - mysqldatabase
    networks:
      - database
    ports:
      - "2020:8080"
    environment:
      JASYPT_ENCRYPTOR_PASSWORD: jmoney_key
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldatabase:3306/jmoneydb?serverTimezone=UTC&useLegacyDatetimeCode=false

networks:
  database: